[tool.poetry]
name = "connection_update-tests"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
asynctest = "^0.13.0"
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
python = "^3.9"
redis = "^4.1.4"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"