name: Prepare
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: "Code quality checks"
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and install poetry
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
        id: setup-poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      #----------------------------------------------
      #       Install dependencies
      #----------------------------------------------
      - name: Install dependencies
        id: install-dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |

          # This will navigate to each subdirectory and install the dependencies
          # If we have a directory that isn't a plugin then it will need to skip it. Currently there is none. 

          for dir in ./*/; do
            cd $dir
            poetry install --no-interaction --no-root
            cd ..
          done
      #----------------------------------------------
      #       Lint plugins
      #----------------------------------------------
      - name: Lint plugins
        id: lint-plugins
        run: |

          # This will navigate to each subdirectory and perform lint checking
          # If we have a directory that isn't a plugin then it will need to skip it. Currently there is none. 

          for dir in ./*/; do
            cd $dir
            poetry run ruff check .
            cd ..
          done
