name: Prepare
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: "Perform lint checking with ruff"
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      #----------------------------------------------
      #       Install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #       Install dev dependencies and lint plugins
      #----------------------------------------------
      - name: Install dev dependencies and lint plugins
        id: install-dev-deps-and-lint
        run: |

          # This will navigate to each subdirectory and install the dev dependencies and perform lint checking
          # If we have a directory that isn't a plugin then it will need to skip it. Currently there is none. 

          for dir in ./*/; do
            cd $dir
            poetry install --only dev
            poetry run ruff check .
            cd ..
          done
